package project;

public class Brin implements java.io.Serializable {
	
	// serial id for serialization (auto generated by java)
	private static final long serialVersionUID = 1L;
	private String minimum;
	private String maximum;
	private int pageID;
	
	public Brin(String minimum, String maximum, int pageID) {
		this.minimum = minimum;
		this.maximum = maximum;
		this.pageID = pageID;
	}

	public String getMinimum() {
		return minimum;
	}

	public String getMaximum() {
		return maximum;
	}

	public int getPageID() {
		return pageID;
	}
	
	
}
