package project;

import java.util.LinkedList;

public class Tuple implements java.io.Serializable
{
	// serial id for serialization (auto generated by java)
	private static final long serialVersionUID = 1L;

	// a linked list of objects that hold the row data, we can use .getClass method to get the type of each object
	private LinkedList<Object> tupleInfo;
	
	//ID of the page that the tuple is stored in, we don't know whether we'll need that yet or no
	//transient means that should not be serialized with the tuple data into the page, it is ignored
	private transient int pageID;

	//constructor
	public Tuple(LinkedList<Object> tupleInfo)
	{
		this.tupleInfo = tupleInfo;
	}

	//getters and setters
	public int getPageID()
	{
		return this.pageID;
	}

	public void setPageID(int p)
	{
		this.pageID = p;
	}

	public LinkedList<Object> getTupleInfo()
	{
		return this.tupleInfo;
	}

	public void setTupleInfo(LinkedList<Object> tupleInfo) {
		this.tupleInfo = tupleInfo;
	}

	//toString method to see the tuple data
	public String toString()
	{
		String s = "";
		for (int i = 0; i < tupleInfo.size(); i++)
		{
			s += tupleInfo.get(i);
			if (i != tupleInfo.size() - 1)
				s += ", ";
		}
		return s;
	}

}
